### ISSUE TITLE
Program error during training

### ISSUE THREAD

**Issue by FrankYii1** [yassouali/CCT#69]
When I am training CCT, the following error will occur. I would like to know how to solve this problem?
Traceback (most recent call last):
  File "/home/d6813/anaconda3/envs/CCT/lib/python3.7/threading.py", line 926, in _bootstrap_inner
    self.run()
  File "/home/d6813/anaconda3/envs/CCT/lib/python3.7/site-packages/tensorboard/summary/writer/event_file_writer.py", line 233, in run
    self._record_writer.write(data)
  File "/home/d6813/anaconda3/envs/CCT/lib/python3.7/site-packages/tensorboard/summary/writer/record_writer.py", line 40, in write
    self._writer.write(header + header_crc + data + footer_crc)
  File "/home/d6813/anaconda3/envs/CCT/lib/python3.7/site-packages/tensorboard/compat/tensorflow_stub/io/gfile.py", line 766, in write
    self.fs.append(self.filename, file_content, self.binary_mode)
  File "/home/d6813/anaconda3/envs/CCT/lib/python3.7/site-packages/tensorboard/compat/tensorflow_stub/io/gfile.py", line 160, in append
    self._write(filename, file_content, "ab" if binary_mode else "a")
  File "/home/d6813/anaconda3/envs/CCT/lib/python3.7/site-packages/tensorboard/compat/tensorflow_stub/io/gfile.py", line 164, in _write
    with io.open(filename, mode, encoding=encoding) as f:
OSError: [Errno 9] Bad file descriptor

**Comment by yassouali** [comment]
OSError is often raised when operations are performed on a file that has been closed or was never properly opened. Check the file path & permissions.
